version: '3.8'

services:
  redis-1:
    hostname: redis-master
    container_name: redis-master
    image: bitnami/redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  redis-2:
    hostname: redis-replica-1
    container_name: redis-replica-1
    image: bitnami/redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 5000:6379
    depends_on:
      - redis-1